In [51]:
# https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html
import torch
import numpy as np

In [52]:
x = torch.ones(2, 2)
x

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [53]:
x.requires_grad 

False

By default, the history of computation will not be tracked. It also uses up a lot of memory

In [54]:
x.requires_grad = True # Alternately, while initialising: x = torch.ones(2, 2, requires_grad=True) would suffice
# Or, inplace setting of the requires_grad flag. Without any arg, the flag is set to True by default
x.requires_grad_()

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [55]:
y = x + 2 # Wow! This is possible with numpy arrays also

In [56]:
print(y)

tensor([[ 3.,  3.],
        [ 3.,  3.]])


In [57]:
print(x.grad_fn) # User-defined variables do not have grad_fn attaribute.
#  grad_fn attribute stores the fxn/operation name, which created this variable

None


In [58]:
print(y.grad_fn)

In [59]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[ 27.,  27.],
        [ 27.,  27.]]) tensor(27.)


In [60]:
print(out.item()) # Obtaining the answer as a numeriacal value, from a tensor

27.0


`variable.mean()` and `variable.sum()` calculates the appropriate mathematical values. Here, variable can be a tensor

In [61]:
out.backward()

In [62]:
x.grad

tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])

In [63]:
print((x ** 2).requires_grad)

True


In [64]:
with torch.no_grad(): # Even if the below-mentioned variables have req grad=True, they will be set to False within this block
    print((x ** 2).requires_grad)    

False


In [66]:
x.data.norm() # Calculates the l2 norm, the euclidean distance or SRSS - square root of sum of squares

tensor(2.)