Tutorial from: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

In [52]:
from __future__ import print_function
import numpy as np

In [4]:
import torch

In [7]:
x = torch.empty(5, 3)

In [8]:
x = torch.rand(5, 3) # constructs a randomly initilised matrix
print(x)

tensor([[ 0.4276,  0.1721,  0.8967],
        [ 0.2128,  0.6588,  0.6611],
        [ 0.3224,  0.1946,  0.6332],
        [ 0.5129,  0.5492,  0.9913],
        [ 0.6156,  0.3300,  0.2688]])


In [12]:
x = torch.zeros(5, 3, dtype=torch.double)
print(x)

tensor([[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]], dtype=torch.float64)


In [18]:
x = torch.tensor([5.5, 3.25], dtype=torch.double)
x

tensor([ 5.5000,  3.2500], dtype=torch.float64)

In [27]:
x = torch.randn(5, 3)
x

tensor([[-1.1917, -1.1569,  0.5925],
        [-0.0161, -0.3889,  1.8597],
        [ 0.0431,  1.3907, -0.0494],
        [ 0.0188,  0.1439, -1.2042],
        [ 0.2607, -1.1721,  2.2679]])

In [28]:
x = torch.randn_like(x) # fills x with normally distributed random numbers.
# Other attributes like input size, layout, device, grad will be obtained from the specified input
x

tensor([[-0.4384, -1.0616,  1.3850],
        [-2.0241,  0.4196,  2.7048],
        [-0.3530,  0.1821, -0.1414],
        [-0.9910,  0.0056,  0.5516],
        [ 0.0669, -2.4027,  0.2348]])

In [29]:
x.size() # this is a tuple.

torch.Size([5, 3])

In [30]:
y = torch.randn(5, 3)
y

tensor([[ 0.4857, -1.0076, -1.3438],
        [ 0.9766, -0.3393,  0.7213],
        [ 0.7549,  1.1650,  1.7177],
        [ 1.6920, -0.8659, -2.0226],
        [-0.9533,  1.0845, -1.1982]])

In [44]:
# Addition
print(x + y)
print(torch.add(x, y))
result = torch.empty(5, 3)
torch.add(x, y, out=result) # specifying the out vector
print(result)

tensor([[ 1.0186, -4.0843, -2.6463],
        [ 0.9057, -0.5982,  4.8687],
        [ 1.9116,  3.6771,  5.0118],
        [ 4.0851, -2.5922, -5.5163],
        [-2.7929,  0.8508, -3.3599]])
tensor([[ 1.0186, -4.0843, -2.6463],
        [ 0.9057, -0.5982,  4.8687],
        [ 1.9116,  3.6771,  5.0118],
        [ 4.0851, -2.5922, -5.5163],
        [-2.7929,  0.8508, -3.3599]])
tensor([[ 1.0186, -4.0843, -2.6463],
        [ 0.9057, -0.5982,  4.8687],
        [ 1.9116,  3.6771,  5.0118],
        [ 4.0851, -2.5922, -5.5163],
        [-2.7929,  0.8508, -3.3599]])


In [ ]:
# All inplace functions are suffixed by " _ "
# Ex. of inplace functions: x.copy_(y), x.t_(y), etc.
print(x)
print(y)
x.add_(y)
print(x)

In [35]:
x[:, 1]

tensor([-3.0768, -0.2589,  2.5121, -1.7263, -0.2337])

In [37]:
x.size()

torch.Size([5, 3])

In [40]:
# Resizing tensors using torch.view(new_size)
x_new1 = x.view(15)
x_new2 = x.view(-1, 5) # the -1'th dimension is inferred from the other dimensions  
print(x.size(), x_new1.size(), x_new2.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [42]:
# individual numbers can be accessed using .item() method
print(x[0][0])
print(x[0][0].item())

tensor(0.5330)
0.5329574346542358


In [46]:
# converting pytorch tensor to numpy array
a = x.numpy()
print(x)
# Change in the way values are printed indicates the conversion
print(a)

tensor([[ 0.5330, -3.0768, -1.3025],
        [-0.0709, -0.2589,  4.1474],
        [ 1.1568,  2.5121,  3.2941],
        [ 2.3930, -1.7263, -3.4937],
        [-1.8396, -0.2337, -2.1617]])
[[ 0.53295743 -3.0767727  -1.3025    ]
 [-0.0709269  -0.2589335   4.1473827 ]
 [ 1.1567613   2.5120926   3.294065  ]
 [ 2.3930383  -1.7262814  -3.4936624 ]
 [-1.8396416  -0.23371553 -2.1616902 ]]


In [50]:
# VERY IMP: a becomes a pointer to x. So any changes to the values in x, gets reflected in a also. 
x.add_(torch.ones(x.size()))
print(x)
print(a)

tensor([[ 2.5330, -1.0768,  0.6975],
        [ 1.9291,  1.7411,  6.1474],
        [ 3.1568,  4.5121,  5.2941],
        [ 4.3930,  0.2737, -1.4937],
        [ 0.1604,  1.7663, -0.1617]])
[[ 2.5329576  -1.0767727   0.6975    ]
 [ 1.9290731   1.7410665   6.1473827 ]
 [ 3.1567612   4.5120926   5.294065  ]
 [ 4.3930383   0.2737186  -1.4936624 ]
 [ 0.16035843  1.7662845  -0.16169024]]


Conversion from <b>numpy array to pytorch tensor</b>: `torch.from_numpy()`


any changes to the values in b, gets reflected in y also

In [ ]:
b = np.ones(5)
y = torch.empty(5)
y = torch.from_numpy(b)
y

In [62]:
print(torch.cuda.is_available())

False


Do Later: Did not understand the CUDA Tensor tutorials properly!